name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Formatting
      working-directory: ${{github.workspace}}/src/service
      run: cargo fmt --check

    - name: Install dependencies
      run: sudo apt install libibus-1.0-dev

    - name: Clippy
      working-directory: ${{github.workspace}}/src/service
      run: cargo clippy --all-features --verbose

    - name: Build
      working-directory: ${{github.workspace}}/src/service
      run: cargo build --all-features --verbose

    - name: Run tests
      working-directory: ${{github.workspace}}/src/service
      run: cargo test --all-features --verbose
